# Yeepack Proxy Gateway Config
connection_throttle: 4000
online_mode: false # Keeps it accessible for Eaglercraft users
ip_forward: true   # Crucial if the target server needs player IPs

servers:
  lobby: # Change this name to your target server name if you want
    motd: '&b&lEaglercraftV &7- &31.16.5 Gateway'
    address: play.jartexnetwork.com:25565 # Put the 1.16.5 server IP here
    restricted: false

listeners:
- query_port: 25577
  motd: '&b&lEaglercraftV &f1.16.5 Bridge'
  tab_list: GLOBAL_PING
  forced_hosts:
    pvp.md-5.net: lobby
  priorities:
  - lobby
  host: 0.0.0.0:25577 # This is the port your EaglercraftXBungee will listen on
  max_players: 100
  force_default_server: true # Makes sure users always go to your 1.16.5 target

# Security & Performance
network_compression_threshold: 256
prevent_proxy_connections: false
enforce_secure_profile: false # MUST be false for 1.8.8 clients to join
